server:
  port: 8980

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://195.208.172.233:8080/alkash
    username: mge
    password: "%xa99vY#juTkf3$em#9%sF$e4U@KKiF#BJ%&5"

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    org.hibernate.type.descriptor.sql: trace